=encoding utf-8

=head1 NAME / 名称

DBICx::Modeler::Generator.ja - (deprecated) DBIx::Class::SchemaとDBICx::Modelerの動的な生成

=head1 概要

このドキュメントはL<DBICx::Modeler::Generator::JA|DBICx::Modeler::Generator::JA>に移動しました。

=head1 著者

=over 4

=item 守屋 雅樹 (Gardejo) (en: MORIYA Masaki, alias Gardejo)

C<< <moriya at cpan dot org> >>,
L<http://gardejo.org/>

=back

=head2 訳註: 訳者

=over 4

=item 守屋 雅樹 (Gardejo) (en: MORIYA Masaki, alias Gardejo)

C<< <moriya at cpan dot org> >>,
L<http://gardejo.org/>

=back

=head1 著作権と使用許諾条件

著作権保有 (c) 2009-2010 守屋 雅樹 (Gardejo)

このモジュールはフリーソフトウェアです。
あなたはこれをPerlと同じように自由に再配布・改変することが出来ます。
詳しくはL<perlgpl|perlgpl>およびL<perlartistic|perlartistic>を参照してください。

使用許諾条件の全文はこのディストリビューションに同梱されているF<LICENSE>ファイルにあります。

=head2 訳註: 著作権と使用許諾条件の原文

Copyright (c) 2009-2010 MORIYA Masaki, alias Gardejo

This module is free software;
you can redistribute it and/or modify it under the same terms as Perl itself.
See L<perlgpl|perlgpl> and L<perlartistic|perlartistic>.

The full text of the license can be found in the F<LICENSE> file
included with this distribution.

=cut
